window.SM_BLOCKS = {
    "controller": { "name": "Controller", "icon": "🎛️", "type": "output", "slot": 4, "img": "assets/controller.png" },
    "button": { "name": "Button", "icon": "🔴", "type": "input", "slot": 0, "img": "assets/button.png" },
    "switch": { "name": "Switch", "icon": "🔛", "type": "input", "slot": 0, "img": "assets/switch.png" },
    "sensor": { "name": "Sensor", "icon": "👁️", "type": "input", "slot": 0, "img": "assets/sensor.png" },
    "timer": { "name": "Timer", "icon": "⏱️", "type": "util", "slot": 3, "img": "assets/timer.png" },
    "logic_gate": { "name": "Logic Gate", "icon": "🧠", "type": "logic", "slot": 2, "img": "assets/logic_gate.png" },
    "gas_engine": { "name": "Gas Engine", "icon": "⛽", "type": "output", "slot": 4, "img": "assets/gas_engine.png" },
    "electric_engine": { "name": "Electric Engine", "icon": "⚡", "type": "output", "slot": 4, "img": "assets/electric_engine.png" },
    "thruster": { "name": "Thruster", "icon": "🚀", "type": "output", "slot": 4, "img": "assets/thruster.png" },
    "bearing": { "name": "Bearing", "icon": "⚙️", "type": "output", "slot": 4, "img": "assets/bearing.png" },
    "piston": { "name": "Piston", "icon": "📏", "type": "output", "slot": 4, "img": "assets/piston.png" },
    "drivers_seat": { "name": "Driver's Seat", "icon": "💺", "type": "input", "slot": 0, "img": "assets/drivers_seat.png" },
    "radio": { "name": "Radio", "icon": "📻", "type": "output", "slot": 4, "img": "assets/radio.png" },
    "fant_chest_fill_detector": { "name": "Chest Fill Detector", "icon": "📶", "type": "output", "slot": 4, "img": "assets/fant_chest_fill_detector.png" },
    "fant_daylight_sensor": { "name": "Daylight Sensor", "icon": "☀️", "type": "input", "slot": 0, "img": "assets/fant_daylight_sensor.png" },
    "fant_suckomatic": { "name": "Suckomatic", "icon": "🌪️", "type": "util", "slot": 3, "img": "assets/fant_suckomatic.png" },
    "fant_smart_chest": { "name": "Smart Chest", "icon": "🧰", "type": "util", "slot": 3, "img": "assets/fant_smart_chest.png" },
    "fant_tank_cannon": { "name": "Tank Cannon", "icon": "💣", "type": "output", "slot": 4, "img": "assets/fant_tank_cannon.png" },
    "fant_robot_detector": { "name": "Robot Detector", "icon": "🤖", "type": "input", "slot": 0, "img": "assets/fant_robot_detector.png" },
    "fant_chemical_lift_engine": { "name": "Chem. Lift Engine", "icon": "🟢", "type": "output", "slot": 4, "img": "assets/fant_chemical_lift_engine.png" },
    "fant_seat_input_converter": { "name": "Seat Converter", "icon": "💺", "type": "output", "slot": 4, "img": "assets/fant_seat_input_converter.png" },
    "fant_angle_sensor": { "name": "Angle Sensor", "icon": "📐", "type": "input", "slot": 0, "img": "assets/fant_angle_sensor.png" },
    "fant_autocrafter": { "name": "Autocrafter", "icon": "🏭", "type": "util", "slot": 3, "img": "assets/fant_autocrafter.png" },
    "fant_wireless_gate": { "name": "Wireless Gate", "icon": "📡", "type": "logic", "slot": 2, "img": "assets/fant_wireless_gate.png" },
    "fant_teleporter": { "name": "Teleporter", "icon": "🌌", "type": "util", "slot": 3, "img": "assets/fant_teleporter.png" },
    "fant_unit_facer": { "name": "Unit Facer", "icon": "🎯", "type": "output", "slot": 4, "img": "assets/fant_unit_facer.png" },
    "fant_hoverpad": { "name": "Hoverpad", "icon": "🛸", "type": "output", "slot": 4, "img": "assets/fant_hoverpad.png" },
    "fant_anchor": { "name": "Fant Anchor", "icon": "⚓", "type": "util", "slot": 3, "img": "assets/fant_anchor.png" },
    "fant_gyroscope": { "name": "Gyroscope", "icon": "⚖️", "type": "input", "slot": 0, "img": "assets/fant_gyroscope.png" },
    "fant_simple_controller": { "name": "Simple Controller", "icon": "🎮", "type": "input", "slot": 0, "img": "assets/fant_simple_controller.png" },
    "fant_pumpjack": { "name": "Pumpjack", "icon": "⛽", "type": "util", "slot": 3, "img": "assets/fant_pumpjack.png" },
    "fant_item_detector": { "name": "Item Detector", "icon": "🔍", "type": "input", "slot": 0, "img": "assets/fant_item_detector.png" },
    "fant_trash_can": { "name": "Trash Can", "icon": "🗑️", "type": "util", "slot": 3, "img": "assets/fant_trash_can.png" },
    "fant_flipflop_gate": { "name": "FlipFlop Gate", "icon": "↔️", "type": "logic", "slot": 2, "img": "assets/fant_flipflop_gate.png" },
    "fant_digital_clock": { "name": "Digital Clock", "icon": "⏰", "type": "output", "slot": 4, "img": "assets/fant_digital_clock.png" },
    "fant_velocity_detector": { "name": "Velocity Detector", "icon": "💨", "type": "output", "slot": 4, "img": "assets/fant_velocity_detector.png" },
    "fant_pump_pipe": { "name": "Pump Pipe", "icon": "🚰", "type": "util", "slot": 3, "img": "assets/fant_pump_pipe.png" },
    "fant_banananator": { "name": "Banananator", "icon": "🍌", "type": "input", "slot": 0, "img": "assets/fant_banananator.png" },
    "fant_packing_gun": { "name": "Packing Gun", "icon": "📦", "type": "input", "slot": 0, "img": "assets/fant_packing_gun.png" },
    "fant_scrapgun": { "name": "Scrapgun", "icon": "🔩", "type": "input", "slot": 0, "img": "assets/fant_scrapgun.png" },
    "fant_multiconnection_tool": { "name": "Multiconnect Tool", "icon": "🔗", "type": "input", "slot": 0, "img": "assets/fant_multiconnection_tool.png" },
    "fant_block_editor": { "name": "Block Editor", "icon": "📝", "type": "input", "slot": 0, "img": "assets/fant_block_editor.png" },
    "fant_measurement_tool": { "name": "Measure Tool", "icon": "📏", "type": "input", "slot": 0, "img": "assets/fant_measurement_tool.png" },
    "fant_modular_track_straight": { "name": "Tank Track (Str)", "icon": "⛓️", "type": "output", "slot": 4, "img": "assets/fant_modular_track_straight.png" },
    "fant_water_wheel": { "name": "Water Wheel", "icon": "🌊", "type": "output", "slot": 4, "img": "assets/fant_water_wheel.png" },
    "fant_propeller": { "name": "Propeller", "icon": "✈️", "type": "output", "slot": 4, "img": "assets/fant_propeller.png" },
    "fant_adjustable_rotor": { "name": "Adj. Rotor", "icon": "🚁", "type": "output", "slot": 4, "img": "assets/fant_adjustable_rotor.png" },
    "fant_plunger_shoes": { "name": "Plunger Shoes", "icon": "👞", "type": "util", "slot": 3, "img": "assets/fant_plunger_shoes.png" },
    "fant_grappling_hook": { "name": "Grappling Hook", "icon": "🎣", "type": "input", "slot": 0, "img": "assets/fant_grappling_hook.png" },
    "fant_remote_gun": { "name": "Remote Gun", "icon": "📡", "type": "input", "slot": 0, "img": "assets/fant_remote_gun.png" }
};
